TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../rtl/uart_transmitter.sv
TOPLEVEL = uart_transmitter
MODULE = test_uart_transmitter
SIM = icarus
WAVES = 1

include $(shell cocotb-config --makefiles)/Makefile.sim