TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../rtl/counter_2bit.sv
TOPLEVEL = counter_2bit
MODULE = test_counter_2bit
SIM = icarus
WAVES = 1

include $(shell cocotb-config --makefiles)/Makefile.sim